### PR TITLE
Fix: Add ZLib

### PR DESCRIPTION
**Pull request by xavierclement**

### CODE REVIEW

**Comment by xavierclement** [comment]
@ju-lit-hein Look to Ubuntu and macOS, I have problem with OpenGL things and I don't eat graphics card at breakfast so I can't figure out this type of problem.

**Comment by ju-lit-hein** [comment]
@xavierclement  I fixed the OpenGL problems, now the problem is server-side and unfortunately I don't spend hundreds of euros on network cables so I can't figure out this type of problem.

**Comment by xavierclement** [comment]
@ju-lit-hein Problem with ECS

**Comment by xavierclement** [comment]
I merge for create new branches to fix

**Review by SizzleUnrlsd — APPROVED** [review]

**Pull request merged**
