### PR TITLE
111 the game

### PR DESCRIPTION
**Pull request by clement-antoine-xavier**

### CODE REVIEW

**Comment by xavierclement** [comment]
@SizzleUnrlsd Do you push on the branch or after the pull request on the main branch

**Comment by SizzleUnrlsd** [comment]
@xavierclement  If you're in a hurry, I'll rebase from the main. If it can wait until tonight, I'll push on the branch.

**Comment by xavierclement** [comment]
@SizzleUnrlsd Ok we will wait for you to push, we are going to fix the windows build

**Review by ElPepitaux — APPROVED** [review]

**Comment by xavierclement** [comment]
@ElPepitaux When do we merge this branch to the main ?

**Pull request merged**
